### ISSUE TITLE
No Program Mode

### ISSUE THREAD

**Issue by colseven** [siku2/hass-komfovent-c5#1]
Hi,
thanks for this HAC. I need the Program Mode but i can't choose it.

![bild 2022-03-08 um 06 08 06](https://user-images.githubusercontent.com/63189272/157170294-6b4bdf6e-0d21-466a-a7fc-34d2c91a2785.jpg)
![bild 2022-03-08 um 06 08 24](https://user-images.githubusercontent.com/63189272/157170315-a8f3b498-4579-43a8-b3f3-b1613064a918.jpg)

**Comment by colseven** [comment]
just add
cls.PROGRAM, LINE 43 in /config/custom_components/komfovent_c5/api/modes.py and it works.

**Comment by siku2** [comment]
> just add
> cls.PROGRAM, LINE 43 in /config/custom_components/komfovent_c5/api/modes.py and it works.

I explicitly disabled it because I didn't fully understand what it does. Can you elaborate on what you need it for?

**Comment by colseven** [comment]
I have created a schedule so that the system then runs exactly in this mode. now, of course, i can control them via hass.
![bild 2022-03-08 um 06 59 05](https://user-images.githubusercontent.com/63189272/157176094-28ee98a4-b9c8-453a-b184-fb47e83b2a3f.jpg)

**Comment by siku2** [comment]
I see, I'd be happy to accept a PR adding the mode back in.

**Comment by siku2** [comment]
I see, I'd be happy to accept a PR adding the mode back in.
