### ISSUE TITLE
Komfovent RHP 600 losing connection

### ISSUE THREAD

**Issue by georgepauna** [siku2/hass-komfovent-c5#22]
I know it's not an integration issue, as i can't properly connect to machine local management page also, but maybe you have some idea.

I think storage got full on the 600 or something. Recently i starting getting unavailable in the integration, a restart fixes it only for a few minutes
As mentioned, even going to 192.168.1.50 i can only login and see first page, any other page is giving error connection lost.

Any idea?

**Comment by georgepauna** [comment]
Here is what the log shows, but as I already said, i think the problem is on the machine side:

This error originated from a custom integration.

Logger: custom_components.komfovent_c5
Source: custom_components/komfovent_c5/api/client.py:56
Integration: Komfovent C5 (documentation, issues)
First occurred: October 4, 2023 at 10:44:52 AM (21357 occurrences)
Last logged: 9:04:32 AM

Unexpected error fetching komfovent_c5 data: Modbus Error: [Connection] Connection lost during request
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 283, in _async_refresh
    self.data = await self._async_update_data()
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/komfovent_c5/__init__.py", line 83, in _async_update_data
    return await KomfoventState.read_all(self.client, self.settings_state)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/komfovent_c5/__init__.py", line 41, in read_all
    active_alarms=await alarms.read_active(),
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/komfovent_c5/api/alarms.py", line 86, in read_active
    count = await self._client.read_u16(self.REG_ACTIVE_ALARMS_COUNT)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/komfovent_c5/api/client.py", line 56, in read_u16
    await self._modbus.read_holding_registers(address, count=1),
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/pymodbus/client/base.py", line 198, in async_execute
    resp = await asyncio.wait_for(req, timeout=self.params.timeout)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/asyncio/tasks.py", line 479, in wait_for
    return fut.result()
           ^^^^^^^^^^^^
pymodbus.exceptions.ConnectionException: Modbus Error: [Connection] Connection lost during request

**Comment by georgepauna** [comment]
In the end it was purely MY network's issue. Changed the router for other reasons, all is good now

**Comment by siku2** [comment]
@georgepauna sorry for never responding, this must've slipped past me. I'm glad you were able to resolve your issue though.
