### ISSUE TITLE
Install not possible

### ISSUE THREAD

**Issue by colseven** [siku2/hass-komfovent-c5#5]
Have now hass-komfovent-c5 completely removed from HACS and then added again, now the configuration flow can no longer be loaded. I've tried it several times now... it doesn't work
![bild 2022-07-31 um 10 22 23](https://user-images.githubusercontent.com/63189272/182017411-8c3ee018-c8a6-4fa9-a180-eb182a9ea222.jpg)

**Comment by colseven** [comment]
Logger: homeassistant.config_entries
Source: config_entries.py:784 
First occurred: 10:32:08 (1 occurrences) 
Last logged: 10:32:08

Error occurred loading configuration flow for integration komfovent_c5: No module named 'pymodbus.client.asynchronous'

**Comment by colseven** [comment]
same ERROR in Version 0.2.5 :(

**Comment by colseven** [comment]
and this - the installation is still not possible

Logger: homeassistant.helpers.service
Source: helpers/service.py:130 
First occurred: 2. August 2022, 22:00:00 (5 occurrences) 
Last logged: 00:30:00

Unable to find referenced entities select.komfovent_operation_mode or it is/they are currently not available
Unable to find referenced entities switch.komfovent_ahu_control or it is/they are currently not available

**Comment by georgepauna** [comment]
Not sure if still relevant, but when installing, select main instead of 0.2.5 and it works with latest HA version (as of now).

**Comment by siku2** [comment]
@colseven your issue might be fixed now that pymodbus 3 has been officially released and all Home Assistant integrations should be using it now, so there should no longer be a version incompatibility.

**Comment by siku2** [comment]
didn't mean to close yet, sorry

**Comment by colseven** [comment]
Now it works, thanks.
